# Generated by Django 6.0.6 on 2026-07-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="notes/"),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
